### ISSUE TITLE
Any example using OIDC client and login to MockPass ?

### ISSUE THREAD

**Issue by cakriwut** [opengovsg/mockpass#109]
Hi,

I am looking for example to configure OIDC client to login to MockPass.
Can you provide me the link or guidance?

Thanks a lot

**Comment by LoneRifle** [comment]
Hi @cakriwut - you may want to look at [singpass-myinfo-oidc-helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper) for some pointers that may help you!
