### ISSUE TITLE
Mockpass no longer defaults to first NRIC if login page disabled

### ISSUE THREAD

**Issue by chadlwilson** [opengovsg/mockpass#120]
In earlier versions before `2.5.0`, mockpass used to default to the first NRIC in the `assertions.saml.singPass` list (or the `MOCKPASS_NRIC` env var) in the returned SAML artifact, if the login page was disabled.

In the current implementation when the login page is disabled, the index in the SAML artifact ID is `-1` which then cannot be looked up, and mockpass returns no NRIC in the `UserName` inside the SAML Artifact; which is a breaking change for most users I imagine.

This seemed to happen in https://github.com/opengovsg/mockpass/commit/7f29add7b0080351f50e307f5cde0cf3a0be5e22 - previous code had a default [here](https://github.com/opengovsg/mockpass/commit/7f29add7b0080351f50e307f5cde0cf3a0be5e22#diff-5d1f11bd220046b41092b3090940a00fb29f8a65aab6dded23bf675ede4c9120L146) which no longer exists in the new implementation [here](https://github.com/opengovsg/mockpass/commit/7f29add7b0080351f50e307f5cde0cf3a0be5e22#diff-5d1f11bd220046b41092b3090940a00fb29f8a65aab6dded23bf675ede4c9120R72-R80)

Was this change intentional?

**Comment by LoneRifle** [comment]
Hey @chadlwilson - thanks for the catch! The change was unintentional, so I'll try to put in a fix for this later today.

**Comment by chadlwilson** [comment]
Thanks! 🙏
