### ISSUE TITLE
Incorrect base64 encoding for at_hash

### ISSUE THREAD

**Issue by pirent** [opengovsg/mockpass#162]
Hey there, the scheme encoding for at_hash supposed to be Base64 URL rather than Base64.
In SingPass OIDC interface specification version 1.5, it states that the payload is Base64 URL encoded.

In file assertion.js
```javascript
const hashAccessToken = (accessToken) => {
  const fullHash = crypto.createHash('sha256')
  fullHash.update(accessToken, 'utf8')
  const fullDigest = fullHash.digest()
  return fullDigest.slice(0, fullDigest.length / 2).toString('base64')
}
```

**Comment by LoneRifle** [comment]
Thanks for pointing this out! if you are to send in a pull request with the corrections we will be happy to have it reviewed and merged.

**Comment by LoneRifle** [comment]
generally speaking however, [base64 strings are URL-safe](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs#:~:text=base64%20strings%20are%20generally%20url-safe), and URL encoding them will mostly result in the same string. If you are able to produce a test case where this is failing, I'll be happy to investigate further.
