### ISSUE TITLE
JWE Decryption

### ISSUE THREAD

**Issue by ekjotsd** [opengovsg/mockpass#223]
Hello, 
I am implementing the mockpass(CorpPass) Login but I am stuck in JWE IDtoken Decryption, would be great help, if someone guide me how to decrypt?

Thanks, 
Ekjot

**Comment by LoneRifle** [comment]
Hi @ekjotsd - if your project is based of one of the following languages, consider using one of the following packages to interact with CorpPass:

### Node.js / JavaScript

- SAML - [spcp-auth-client](https://github.com/opengovsg/spcp-auth-client)
- OIDC - [singpass-myinfo-oidc-helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper/) (note that CorpPass OIDC is currently being implemented)

### Ruby

- SAML - [libcorppass](https://github.com/gdsace/libcorppass)

### Kotlin
- SAML - [svc-auth](https://github.com/gdsace/svc-auth)

**Comment by ekjotsd** [comment]
Hi,
Thanks for your prompt response, but actually i am integrating the same(OIDC) thing in c# which further will be used in some other technology (Outsystems) in which i manage to get the  JWE ID token( 4 Dots) from the web service but the problem is i don't know how to decrypt that token to get the user info.

**Comment by LoneRifle** [comment]
You may refer to spcp-auth-client or singpass-myinfo-oidc-helper to understand the relevant implementation details, and port them over to Outsystems. Hope that helps!
