### ISSUE TITLE
Singpass UUID?

### ISSUE THREAD

**Issue by ahzhezhe** [opengovsg/mockpass#23]
Does SingPass data payload includes an UUID which I can use it to identify my user, instead of using & storing their NRIC?
If it does, will you update mock-pass to included the UUID?

**Comment by LoneRifle** [comment]
Hello! To our knowledge, the payload that comes from SingPass does not contain any identifiers other than the NRIC.

Just so that I can better address your needs... What are you trying to do? What is your use case?

**Comment by ahzhezhe** [comment]
The system I am working on is in public cloud and is not authorised to store NRIC, I wonder is there a way to identify a user without storing NRIC?

**Comment by LoneRifle** [comment]
We at @opengovsg have sgID, a product that addresses exactly this problem. Could you visit our microsite [here](https://id.gov.sg) and see if it suits your needs?

**Comment by LoneRifle** [comment]
MockPass 2.1 now implements SingPass OIDC, which returns both a uuid and the NRIC. Hope this helps.
