### ISSUE TITLE
Is it possible to modify the project to mock the auth code grant flow?

### ISSUE THREAD

**Issue by weirdyang** [opengovsg/mockpass#381]
In particular the flow with client assertion jwt? https://stg-id.singpass.gov.sg/docs/authorization/api#_authorization_code_grant_authenticated_with_client_assertion_jwt

I’m trying to learn how to do this with .net core, but am now stuck at the part of testing. Will I be able to use this project to generate the id_tokens?

**Comment by LoneRifle** [comment]
You should be able to, given that mockpass does not actually check for the deprecated client secret or a client assertion jwt. Hope that helps.
