### ISSUE TITLE
[MyInfo] incorrect baseString for signature verification

### ISSUE THREAD

**Issue by randName** [opengovsg/mockpass#457]
# **Describe the bug**
The [`baseString` generator](https://github.com/opengovsg/mockpass/blob/master/lib/crypto/myinfo-signature.js#L34-L68) currently hardcodes the template, which results in a verification failure.

There is an implementation over at the [MyInfo Helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper/blob/master/src/util/SigningUtil.ts#L80-L89) for reference.

### `POST` request (`token`)
helper `baseString`
```
POST&http://localhost:5156/myinfo/v3/token&app_id=CNX&client_id=CNX&client_secret=[...]&code=[...]&grant_type=authorization_code&nonce=166780413703300&redirect_uri=http://localhost:8000/auth/profile/edit&signature_method=RS256&state=uU3tXeRyrhOLyLZm&timestamp=1667804137033
```

mockpass `baseString` (missing `state` param)
```
POST&http://localhost:5156/myinfo/v3/token&app_id=CNX&client_id=CNX&client_secret=[...]&code=[...]&grant_type=authorization_code&nonce=166780413703300&redirect_uri=http://localhost:8000/auth/profile/edit&signature_method=RS256&timestamp=1667804137033
```

### `GET` request (`person`)
helper `baseString`
```
GET&http://localhost:5156/myinfo/v3/person/S***/&app_id=CNX&attributes=uinfin,name,regadd,email,mobileno&client_id=CNX&nonce=166780366263900&signature_method=RS256&sp_esvcId=MYINFO-CONSENTPLATFORM&timestamp=1667803662639
```

mockpass `baseString` (missing `sp_esvcId` param)
```
GET&http://localhost:5156/myinfo/v3/person/S***/&app_id=CNX&attributes=uinfin,name,regadd,email,mobileno&client_id=CNX&nonce=166780366263900&signature_method=RS256&timestamp=1667803662639 
```

# **Additional context**
I can fix it if I have some spare capacity, but not anytime this week unfortunately.

**Comment by LoneRifle** [comment]
The `/person` issue you raised is #430; that endpoint is for the KYC service and not the TUO one. I'm unsure how we can resolve this right now given dependencies by users on KYC behaviour for now.

`/token` is indeed missing state as part of the base string (not sure when that was introduced though...). Feel free to fix this one and I'll cut a release for it later on!

**Comment by randName** [comment]
I believe the request signing mechanism is the same for both [TUO](https://public.cloud.myinfo.gov.sg/myinfo/tuo/myinfo-tuo-specs.html#section/Security/Request-Signing) and [KYC](https://public.cloud.myinfo.gov.sg/myinfo/api/myinfo-kyc-v3.1.0.html#section/Security/Request-Signing), since both code samples just merge all the parameters and sort them for the `baseString`

On mockpass side it shouldn't matter which endpoint the request is for as the KYC version would not contain the `sp_esvcId` param. Likewise the `state` param is optional and thus the verification step needs to construct the `baseString` based on the incoming request params

**Comment by LoneRifle** [comment]
Correct, the signing mechanism is the same. If you're comfortable with following what the clients do rather than having a hard-coded list of params, I'll rework the impl

**Comment by randName** [comment]
If there is a concern with unknown parameters then there can be an array of all possible known keys that are used (which also eliminates the sorting step), e.g.
```js
const knownKeys = [
  'app_id',
  'attributes',
  // ...
  'sp_esvcId',
  'state',
  // ...
]

const baseString = `${method}&${path}&${new URLSearchParams(knownKeys.map((k) => [k, params[k]]))}`
```

but I don't feel there is a major concern since it is a mock service
