### ISSUE TITLE
Failed to fetch RP JWKS from specified endpoint: fetch is not defined

### ISSUE THREAD

**Issue by ritikchopra-cldcvr** [opengovsg/mockpass#515]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:5156/singpass/v2/token
2. my data req.body is 
req.body = {
grant_type: 'authorization_code',
  code: 'S1234567A',
  client_id: 'S1234567A',
  redirect_uri: 'http://localhost:4444/assert',
  client_assertion_type: 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
  client_assertion: 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkJ1WGZEaXYxQWZ2T3dSREM5RDNXODBXMFFtVGRQbmlrWnVyblFiNm1MdlUifQ.eyJpYXQiOjE2Nzk1OTc4NTIsImV4cCI6MTY3OTU5Nzk3MiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTU2L3NpbmdwYXNzL3YyIiwiaXNzIjoiUzEyMzQ1NjdBIiwic3ViIjoiUzEyMzQ1NjdBIn0.JScopi8LQUdBEViP-P99aqHVfdLIu0eyEL0ZyyMOBdSpbDuRxJnKwGiJHtFfNCKDG94nm7WrnI-Qy4JfZ5_qLg'
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Os - MacOs
Browser - opera/chrome
version - latest

**Additional context**

Requesting { method: 'post', url: 'http://localhost:5156/singpass/v2/token' }
Error occurred while responding to request {
  method: 'post',
  url: 'http://localhost:5156/singpass/v2/token',
  status: 400,
  data: 'Failed to fetch RP JWKS from specified endpoint: fetch is not defined'
}

<img width="602" alt="image" src="https://user-images.githubusercontent.com/100136087/227322361-699747c2-cb92-42e3-9cae-326543aa68ab.png">

**Comment by ritikchopra-cldcvr** [comment]
index.js

`import express from 'express'
import cookieParser from 'cookie-parser'
import { Singpass } from "@govtechsg/singpass-myinfo-oidc-helper"

const key1 = {
    crv: 'P-256',
    alg: ['ES256'],
    ext: false,
    x: 'Sp3KpzPjwcCF04_W2GvSSf-vGDvp3Iv2kQYqAjnMB-Y',
    y: 'lZmecT2quXe0i9f7b4qHvDAFDpxs0oxCoJx4tOOqsks',
    d: 'hRVo5TGE_d_4tQC1KEQIlCdo9rteZmLSmaMPpFOjeDI',
    kty: 'EC',
}

const key = {
    "key": JSON.parse(JSON.stringify(key1)),
    "format": 'json',
    "alg": 'ES256',
}   
  

const server = new Singpass.NdiOidcHelper({
    authorizationUrl: 'http://localhost:5156/singpass/v2/authorize',
    logoutUrl: 'http://localhost:5156/singpass/logout ',
    tokenUrl: 'http://localhost:5156/singpass/v2/token',
    clientID: 'S1234567A',
    clientSecret: 'ef39a074-b64d-4990-a937-6f80772e2bb8',
    redirectUri: 'http://localhost:4444/assert',
    oidcConfigUrl: 'http://localhost:5156/singpass/v2/.well-known/openid-configuration',
    clientID: 'S1234567A',
    redirectUri: 'http://localhost:4444/assert',
    jweDecryptKey: JSON.parse(JSON.stringify(key)),
    clientAssertionSignKey: JSON.parse(JSON.stringify(key)),
})

const app = express()
app.use(cookieParser())

app.get('/login', async (req, res) => {
  const redirectURL = await server.constructAuthorizationUrl('kiosk001', 'S8979373D', 'http://localhost:5156/singpass/v2/authorize')
  res.cookie('connect.sid', '').redirect(redirectURL)
})

app.get('/assert', async (req, res) => {
  const token = await server.getTokens("S1234567A")
  console.log("singpass", token)
})

app.get('/logout', (req, res, next) => {
    const out = client.logoutOfSession()
    res.send(200).send(out)
})

const port = process.env.PORT || 4444
app.listen(4444, () => console.log(`Listening on port ${port}`))
`

I'm trying to get the token but getting errors

**Comment by ritikchopra-cldcvr** [comment]
index.js

`import express from 'express'
import cookieParser from 'cookie-parser'
import { Singpass } from "@govtechsg/singpass-myinfo-oidc-helper"

const key1 = {
    crv: 'P-256',
    alg: ['ES256'],
    ext: false,
    x: 'Sp3KpzPjwcCF04_W2GvSSf-vGDvp3Iv2kQYqAjnMB-Y',
    y: 'lZmecT2quXe0i9f7b4qHvDAFDpxs0oxCoJx4tOOqsks',
    d: 'hRVo5TGE_d_4tQC1KEQIlCdo9rteZmLSmaMPpFOjeDI',
    kty: 'EC',
}

const key = {
    "key": JSON.parse(JSON.stringify(key1)),
    "format": 'json',
    "alg": 'ES256',
}   
  

const server = new Singpass.NdiOidcHelper({
    authorizationUrl: 'http://localhost:5156/singpass/v2/authorize',
    logoutUrl: 'http://localhost:5156/singpass/logout ',
    tokenUrl: 'http://localhost:5156/singpass/v2/token',
    clientID: 'S1234567A',
    clientSecret: 'ef39a074-b64d-4990-a937-6f80772e2bb8',
    redirectUri: 'http://localhost:4444/assert',
    oidcConfigUrl: 'http://localhost:5156/singpass/v2/.well-known/openid-configuration',
    clientID: 'S1234567A',
    redirectUri: 'http://localhost:4444/assert',
    jweDecryptKey: JSON.parse(JSON.stringify(key)),
    clientAssertionSignKey: JSON.parse(JSON.stringify(key)),
})

const app = express()
app.use(cookieParser())

app.get('/login', async (req, res) => {
  const redirectURL = await server.constructAuthorizationUrl('kiosk001', 'S8979373D', 'http://localhost:5156/singpass/v2/authorize')
  res.cookie('connect.sid', '').redirect(redirectURL)
})

app.get('/assert', async (req, res) => {
  const token = await server.getTokens("S1234567A")
  console.log("singpass", token)
})

app.get('/logout', (req, res, next) => {
    const out = client.logoutOfSession()
    res.send(200).send(out)
})

const port = process.env.PORT || 4444
app.listen(4444, () => console.log(`Listening on port ${port}`))
`

**Comment by ritikchopra-cldcvr** [comment]
Index.js

```
import express from 'express'
import cookieParser from 'cookie-parser'
import { Singpass } from "@govtechsg/singpass-myinfo-oidc-helper"

const key1 = {
    crv: 'P-256',
    alg: ['ES256'],
    ext: false,
    x: 'Sp3KpzPjwcCF04_W2GvSSf-vGDvp3Iv2kQYqAjnMB-Y',
    y: 'lZmecT2quXe0i9f7b4qHvDAFDpxs0oxCoJx4tOOqsks',
    d: 'hRVo5TGE_d_4tQC1KEQIlCdo9rteZmLSmaMPpFOjeDI',
    kty: 'EC',
}

const key = {
    "key": JSON.parse(JSON.stringify(key1)),
    "format": 'json',
    "alg": 'ES256',
}   
  

const server = new Singpass.NdiOidcHelper({
    authorizationUrl: 'http://localhost:5156/singpass/v2/authorize',
    logoutUrl: 'http://localhost:5156/singpass/logout ',
    tokenUrl: 'http://localhost:5156/singpass/v2/token',
    clientID: 'S1234567A',
    clientSecret: 'ef39a074-b64d-4990-a937-6f80772e2bb8',
    redirectUri: 'http://localhost:4444/assert',
    oidcConfigUrl: 'http://localhost:5156/singpass/v2/.well-known/openid-configuration',
    clientID: 'S1234567A',
    redirectUri: 'http://localhost:4444/assert',
    jweDecryptKey: JSON.parse(JSON.stringify(key)),
    clientAssertionSignKey: JSON.parse(JSON.stringify(key)),
})

const app = express()
app.use(cookieParser())

app.get('/login', async (req, res) => {
  const redirectURL = await server.constructAuthorizationUrl('kiosk001', 'S8979373D', 'http://localhost:5156/singpass/v2/authorize')
  res.cookie('connect.sid', '').redirect(redirectURL)
})

app.get('/assert', async (req, res) => {
  const token = await server.getTokens("S1234567A")
  console.log("singpass", token)
})

app.get('/logout', (req, res, next) => {
    const out = client.logoutOfSession()
    res.send(200).send(out)
})

const port = process.env.PORT || 4444
app.listen(4444, () => console.log(`Listening on port ${port}`))

```

I'm trying to get token but unable

Please help me here

**Comment by justin-tay** [comment]
This has nothing to do with this repository.

You are attempting to use the global `fetch` api on an environment where it is not defined.

For node the `fetch` api has been implemented since node 18. If you need to target an earlier version of node then you need something like `node-fetch`.
