### ISSUE TITLE
sgID integration does not implement OAuth scopes

### ISSUE THREAD

**Issue by kenjin-work** [opengovsg/mockpass#539]
**Is your feature request related to a problem? Please describe.**
Current sgID integration does not allow scopes to be set from the user. Authorise token is returned with just the default `openid` scope set, and the `userinfo` is hardcoded to return NRIC, DOB and name.

**Describe the solution you'd like**
Mockpass should support OAuth scopes specified by the sgID data catalog https://docs.id.gov.sg/data-catalog.

**Describe alternatives you've considered**
NIL

**Additional context**
Relevant code is at https://github.com/opengovsg/mockpass/blob/8948e21b041d8bc7c6bdbb141cb134e307bf84cf/lib/express/sgid.js#L60-L162
.

I am interested in working on a fix for this.

**Comment by LoneRifle** [comment]
@kenjin-work - go ahead!
