### ISSUE TITLE
MockPass Children scopes are not as granular as MyInfo documentation

### ISSUE THREAD

**Issue by kenjin-work** [opengovsg/mockpass#548]
**Describe the bug**
On Mockpass, ``childrenbirthrecords` is a single scope, which gives access to all children birth record info.

However, on MyInfo, the developer documentation doesn't include this scope. Instead, it only has sub-scopes of `childrenbirthrecords`, allowing the application query for specific parts of the `childrenbirthrecords` https://public.cloud.myinfo.gov.sg/myinfo/api/myinfo-kyc-v4.0.html#section/Authentication/OAuth2

We should thus follow MyInfo' dev docs.

**Additional context**
I will work on this.

**Comment by LoneRifle** [comment]
@kenjin-work is this the same issue as #480 ?

**Comment by kenjin-work** [comment]
Yes it is. Closing as duplicate of #480.

**Comment by LoneRifle** [comment]
Duplicate of #480
