### ISSUE TITLE
EC encryption keys should be allowed to have any ECDH-ES+A___KW alg

### ISSUE THREAD

**Issue by cflee** [opengovsg/mockpass#606]
**Describe the bug**
RP encryption JWKs with `kty` = EC are rejected if the `alg` doesn't match a specific `crv` value in these specific pairings:

- `crv = P-521, alg = ECDH-ES+A256KW`
- `crv = P-384, alg = ECDH-ES+A192KW`
- `crv = P-256, alg = ECDH-ES+A128KW`

**To Reproduce**
1. Run mockpass v4.0.9, that points to an RP JWKS containing a single encryption key that `kty = EC, use = enc, crv = P-521, alg = ECDH-ES+A128KW`
2. Perform an authorize and token endpoint request

**Expected behavior**
RP encryption JWKs with `kty` = EC are accepted even if the `alg` doesn't match the specific `crv` pairing as stated above. For example, `crv = P-521, alg = ECDH-ES+A128KW` or `crv = P-256, alg = ECDH-ES+A256KW`.

After the preference for encryption key with stronger `crv`, there should be a preference for encryption key with stronger key wrapping `alg`.

**Screenshots**
This is the message logged by mockpass when there's a token endpoint request from an RP with an `crv = P-521` and `alg = ECDH-ES+A128KW` encryption key.

```
No suitable encryption key found [
  {
    kty: 'EC',
    use: 'sig',
    crv: 'P-256',
    kid: 'dynamic-signing-key',
    x: 'tGdp1o6sVuEMNIujpi5WijRsHRpiTp87drJisMvoOKk',
    y: 'tCqYkI8STOU1XqDvbvYFLfOlg46AomuE3arnbtPCflQ'
  },
  {
    kty: 'EC',
    use: 'enc',
    crv: 'P-521',
    kid: 'dynamic-encryption-key',
    x: 'AQK6zACJcuXYwyymgwG6OjQievqHN7h-Vit6QtMNXnnry-c93aYRyp-sp89zhi6zPlTIblDAjqIZJKhJVUGkQMCY',
    y: 'AdSiDXgpBU927IpUXN2LqvU8xTdXwCf82mBjh_7G7jkNV73rfzU-N3U-PgjNSaJ8MQLzsyUdlOTImUoVx6J0ZJq_',
    alg: 'ECDH-ES+A128KW'
  }
]
```

**Additional context**
This key selection behaviour is newly introduced in v4.0.9. 

I haven't found anything in [RFC 7516](https://datatracker.ietf.org/doc/html/rfc7516) (JWE) or [RFC 7518](https://datatracker.ietf.org/doc/html/rfc7518) that suggests that the `crv` needs to be paired with the `alg`. 

The [Singpass NDI spec](https://stg-id.singpass.gov.sg/docs/authorization/api#_key_preference) specifies in the encryption key preference logic that "prefer EC keys with stronger `alg` key wrapping _above_ weaker ones", which is consistent with the understanding that there should be multiple `alg` acceptable for EC encryption keys.

**Comment by LoneRifle** [comment]
Thanks! @justin-tay - could I get you to look into this if you have the time?
