### ISSUE TITLE
idToken Format in OIDC

### ISSUE THREAD

**Issue by royooooooo** [opengovsg/mockpass#69]
If you use the tool like keycloak to integrate mockpass by oidc, one of the necessary steps is to verify nonce, but it's not in the code yet.

Another thing, should the official singPass idToken return a base64 encrypted string or a JSON string? it's JSON string in the code now.

**Comment by LoneRifle** [comment]
Hey @royooooooo ,
the `id_token` returned is a signed and JWE-encrypted JSON string, I assume that's what you meant to say:
https://github.com/opengovsg/mockpass/blob/009ae8792bf1f9689a0729f19bd8a985d75453c9/lib/express/oidc.js#L69-L83

This is expected by singpass-myinfo-oidc-helper, a helper library for SingPass and MyInfo OIDC integrations, and against which mockpass is built:

https://github.com/GovTechSG/singpass-myinfo-oidc-helper/blob/9bf1b3c201e86520aa4abe1afc0a15b66b2d2f47/src/singpass/singpass-helper.ts#L147-L159

The lack of nonce checks is deliberate, given that mockpass is not meant to be used as a watertight OIDC implementation, but as a substitute for SingPass on developer machines and automated testing. I'm happy to take a PR from you that implements nonce checks, but it might be a while before I do it myself.

**Comment by royooooooo** [comment]
We want to use the token interface to simulate singpass return, but singpass now returns a [encrypt string by base64](https://public.cloud.myinfo.gov.sg/sglogin/SingPass-login-specs-v0.1.html#operation/tokenAuth),  which is not consistent with the real return. It's confusing when we're developing it.

**Comment by LoneRifle** [comment]
> We want to use the token interface to simulate singpass return, but singpass now returns a [encrypt string by base64](https://public.cloud.myinfo.gov.sg/sglogin/SingPass-login-specs-v0.1.html#operation/tokenAuth), which is not consistent with the real return. It's confusing when we're developing it.

the sample response given in the link is a signed and encrypted JWE as described earlier and as supported by both mockpass and singpass-myinfo-oidc-helper. If there are inconsistencies, please get in touch with the NDI team.

**Comment by royooooooo** [comment]
Thank you for explaining. I'll fork this repo and make some change to apply our project.

**Comment by LoneRifle** [comment]
If you implement nonce checking, feel free to send a PR. I'll be happy to review.

**Comment by LoneRifle** [comment]
Fixed in #76
