### ISSUE TITLE
OIDC support for CorpPass

### ISSUE THREAD

**Issue by afrizalchen** [opengovsg/mockpass#79]
Hi,
Is it in the roadmap to support OIDC for CorpPass? 
Thank you.

**Comment by LoneRifle** [comment]
Hi @afrizalchen ! This question really should be for the @ndi-trusted-data team in GovTech Singapore, as they are responsible for SingPass and CorpPass. MockPass serves as a developer tool by mimicking those services, and is maintained by a separate team.

Hope this helps!
