### ISSUE TITLE
How to register my application as a client to get the clientid and client secret.

### ISSUE THREAD

**Issue by only4study** [opengovsg/mockpass#97]
Is there a register service to register my client to get the client id and client secret. I don't find anything about this. As a OIDC auth service, i think there will be a register service, where we can configure the client information.

**Comment by LoneRifle** [comment]
Hi @only4study ,

You may go to [NDI's contact page](https://www.ndi-api.gov.sg/contact) to send an email about onboarding with SingPass, which is one of the Trusted Identity APIs that the NDI division maintains. Hope that helps!
